# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('epoch', models.CharField(blank=True, max_length=255, null=True)),
                ('release', models.CharField(blank=True, max_length=255, null=True)),
                ('arch', models.CharField(max_length=255)),
                ('packagetype', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(max_length=255)),
                ('release', models.CharField(blank=True, max_length=255, null=True)),
                ('packagetype', models.CharField(blank=True, choices=[('R', 'rpm'), ('D', 'deb'), ('U', 'unknown')], max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('arch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arch.PackageArchitecture')),
            ],
            options={
                'ordering': ('name', 'epoch', 'version', 'release', 'arch'),
            },
        ),
        migrations.CreateModel(
            name='PackageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PackageUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.BooleanField(default=False)),
                ('newpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newpackage', to='packages.Package')),
                ('oldpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldpackage', to='packages.Package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.PackageName'),
        ),
        migrations.AlterUniqueTogether(
            name='packageupdate',
            unique_together=set([('oldpackage', 'newpackage', 'security')]),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('name', 'epoch', 'version', 'release', 'arch', 'packagetype')]),
        ),
    ]
