# Generated by Django 3.2.25 on 2025-02-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repotype',
            field=models.CharField(choices=[('R', 'rpm'), ('D', 'deb'), ('A', 'arch'), ('G', 'gentoo')], max_length=1),
        ),
    ]
