# Generated by Django 4.2.19 on 2025-03-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_migrate_to_tz_aware'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirror',
            old_name='file_checksum',
            new_name='package_checksum',
        ),
    ]
