# Generated by Django 4.2.19 on 2025-03-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_rename_file_checksum_mirror_package_checksum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirror',
            old_name='package_checksum',
            new_name='packages_checksum',
        ),
    ]
