# Generated by Django 4.2.19 on 2025-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0005_rename_package_checksum_mirror_packages_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='errata_checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mirror',
            name='modules_checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
