# Generated by Django 4.2.28 on 2026-02-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0006_mirror_errata_checksum_mirror_modules_checksum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mirror',
            options={'ordering': ['url'], 'verbose_name_plural': 'Mirrors'},
        ),
        migrations.AlterModelOptions(
            name='mirrorpackage',
            options={'ordering': ['mirror', 'package']},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['name'], 'verbose_name_plural': 'Repositories'},
        ),
    ]
