# Generated by Django 4.2.28 on 2026-02-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0007_alter_mirror_options_alter_mirrorpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='packages_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
