# Generated by Django 4.2.28 on 2026-02-11

from django.db import migrations


def backfill_mirror_counts(apps, schema_editor):
    """Backfill packages_count for existing mirrors."""
    Mirror = apps.get_model('repos', 'Mirror')
    for mirror in Mirror.objects.all():
        mirror.packages_count = mirror.packages.count()
        mirror.save(update_fields=['packages_count'])


def reverse_backfill(apps, schema_editor):
    """No-op reverse."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0008_mirror_packages_count'),
    ]

    operations = [
        migrations.RunPython(backfill_mirror_counts, reverse_backfill),
    ]
