# Generated by Django 3.2.19 on 2023-12-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('arch', '0001_initial'),
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('stream', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=255, unique=True)),
                ('arch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arch.packagearchitecture')),
                ('packages', models.ManyToManyField(blank=True, to='packages.Package')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.repository')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ('name',),
            },
        ),
    ]
