# Generated by Django 4.2.19 on 2025-03-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name', 'stream'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
    ]
