# Generated by Django 4.2.25 on 2025-11-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0001_initial'),
        ('repos', '0006_mirror_errata_checksum_mirror_modules_checksum'),
        ('modules', '0004_alter_module_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'stream', 'version', 'context', 'arch', 'repo')},
        ),
    ]
