# Generated by Django 4.2.28 on 2026-03-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_module_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='context',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='module',
            name='stream',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='module',
            name='version',
            field=models.CharField(max_length=128),
        ),
    ]
