# Generated by Django 4.2.28 on 2026-04-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_module_context_alter_module_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name', 'stream', 'version', 'context', 'arch', 'repo'), name='unique_module'),
        ),
    ]
