# Generated by Django 3.2.19 on 2023-12-11 22:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ipaddress', models.GenericIPAddressField()),
                ('reversedns', models.CharField(blank=True, max_length=255, null=True)),
                ('check_dns', models.BooleanField(default=False)),
                ('kernel', models.CharField(max_length=255)),
                ('lastreport', models.DateTimeField()),
                ('reboot_required', models.BooleanField(default=False)),
                ('host_repos_only', models.BooleanField(default=True)),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ('hostname',),
            },
        ),
        migrations.CreateModel(
            name='HostRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
    ]
