# Generated by Django 3.2.19 on 2023-12-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('packages', '0001_initial'),
        ('arch', '0001_initial'),
        ('operatingsystems', '0002_initial'),
        ('hosts', '0001_initial'),
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostrepo',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.repository'),
        ),
        migrations.AddField(
            model_name='host',
            name='arch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arch.machinearchitecture'),
        ),
        migrations.AddField(
            model_name='host',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain'),
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatingsystems.os'),
        ),
        migrations.AddField(
            model_name='host',
            name='packages',
            field=models.ManyToManyField(blank=True, to='packages.Package'),
        ),
        migrations.AddField(
            model_name='host',
            name='repos',
            field=models.ManyToManyField(blank=True, through='hosts.HostRepo', to='repos.Repository'),
        ),
        migrations.AddField(
            model_name='host',
            name='updates',
            field=models.ManyToManyField(blank=True, to='packages.PackageUpdate'),
        ),
        migrations.AlterUniqueTogether(
            name='hostrepo',
            unique_together={('host', 'repo')},
        ),
    ]
