# Generated by Django 4.2.18 on 2025-02-04 23:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('hosts', '0003_host_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='tags',
        ),
        migrations.AddField(
            model_name='host',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
