# Generated by Django 4.2.18 on 2025-02-04 23:37

import taggit.managers
from django.apps import apps
from django.db import migrations

try:
    import tagging  # noqa
except ImportError:
    pass


def check_tagging_tag_field_exists(app_label, model_name, field_name):
    Model = apps.get_model(app_label, model_name)
    fields = Model._meta.get_fields()
    for field in fields:
        if field.name == field_name and 'tagging' in str(field.related_model):
            return True
    return False


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('hosts', '0003_host_modules'),
    ]

    if check_tagging_tag_field_exists('hosts', 'Host', 'tags'):
        operations = [
            migrations.RemoveField(
                model_name='host',
                name='tags',
            )
        ]
    else:
        operations = []

    operations.append(
        migrations.AddField(
            model_name='host',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        )
    )
