# Generated by Django 4.2.18 on 2025-02-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_remove_host_tags_host_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='os',
            new_name='osvariant',
        ),
    ]
