# Generated by Django 4.2.19 on 2025-02-28 19:53

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('hosts', '0006_migrate_to_tz_aware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
