# Generated by Django 4.2.28 on 2026-02-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_host_errata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostrepo',
            options={'ordering': ['host', 'repo']},
        ),
    ]
