# Generated by Django 4.2.28 on 2026-02-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_alter_hostrepo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='bug_updates_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='errata_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='packages_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='sec_updates_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
