# Generated by Django 4.2.28 on 2026-02-11

from django.db import migrations


def backfill_host_counts(apps, schema_editor):
    """Backfill cached count fields for existing hosts."""
    Host = apps.get_model('hosts', 'Host')
    for host in Host.objects.all():
        host.sec_updates_count = host.updates.filter(security=True).count()
        host.bug_updates_count = host.updates.filter(security=False).count()
        host.packages_count = host.packages.count()
        host.errata_count = host.errata.count()
        host.save(update_fields=[
            'sec_updates_count', 'bug_updates_count',
            'packages_count', 'errata_count'
        ])


def reverse_backfill(apps, schema_editor):
    """No-op reverse - counts will be recalculated on next report."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_host_bug_updates_count_host_errata_count_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_host_counts, reverse_backfill),
    ]
