# Generated by Django 4.2.28 on 2026-04-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_backfill_cached_counts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostrepo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='hostrepo',
            constraint=models.UniqueConstraint(fields=('host', 'repo'), name='unique_hostrepo'),
        ),
    ]
