# Generated by Django 3.2.25 on 2025-02-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0001_initial'),
        ('operatingsystems', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='arch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arch.machinearchitecture'),
        ),
    ]
