# Generated by Django 4.2.15 on 2025-01-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operatingsystems', '0003_osgroup_codename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='osgroup',
            unique_together={('name', 'codename')},
        ),
    ]
