# Generated by Django 4.2.19 on 2025-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatingsystems', '0005_rename_osgroup_osrelease_rename_os_osvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osrelease',
            name='cpe_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='osvariant',
            name='codename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
