# Generated by Django 4.2.28 on 2026-02-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatingsystems', '0008_alter_osrelease_options_alter_osvariant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='osvariant',
            name='hosts_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
