# Generated by Django 4.2.28 on 2026-02-11

from django.db import migrations


def backfill_osvariant_counts(apps, schema_editor):
    """Backfill hosts_count for existing osvariants."""
    OSVariant = apps.get_model('operatingsystems', 'OSVariant')
    Host = apps.get_model('hosts', 'Host')
    for osvariant in OSVariant.objects.all():
        osvariant.hosts_count = Host.objects.filter(osvariant=osvariant).count()
        osvariant.save(update_fields=['hosts_count'])


def reverse_backfill(apps, schema_editor):
    """No-op reverse."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('operatingsystems', '0009_osvariant_hosts_count'),
        ('hosts', '0012_backfill_cached_counts'),
    ]

    operations = [
        migrations.RunPython(backfill_osvariant_counts, reverse_backfill),
    ]
