# Generated by Django 4.2.28 on 2026-03-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatingsystems', '0010_backfill_osvariant_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osrelease',
            name='codename',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='osrelease',
            name='cpe_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='osrelease',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
