# Generated by Django 4.2.28 on 2026-04-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatingsystems', '0011_alter_osrelease_codename_alter_osrelease_cpe_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='osrelease',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='osrelease',
            constraint=models.UniqueConstraint(fields=('name', 'codename', 'cpe_name'), name='unique_osrelease'),
        ),
    ]
