# Generated by Django 4.2.15 on 2025-01-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erratumreference',
            name='er_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
