# Generated by Django 3.2.25 on 2025-02-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_delete_erratum_delete_erratumreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Package Category',
                'verbose_name_plural': 'Package Categories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='package',
            name='packagetype',
            field=models.CharField(blank=True, choices=[('R', 'rpm'), ('D', 'deb'), ('A', 'arch'), ('G', 'gentoo'), ('U', 'unknown')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packagecategory'),
        ),
    ]
