# Generated by Django 4.2.18 on 2025-02-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Erratum',
        ),
        migrations.DeleteModel(
            name='ErratumReference',
        ),
    ]
