# Generated by Django 3.2.25 on 2025-02-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0001_initial'),
        ('packages', '0002_auto_20250207_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'epoch', 'version', 'release', 'arch', 'packagetype', 'category')},
        ),
    ]
