# Generated by Django 4.2.19 on 2025-03-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_package_options_alter_packagecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packagetype',
            field=models.CharField(blank=True, choices=[('R', 'rpm'), ('D', 'deb'), ('A', 'pkgbuild'), ('G', 'ebuild'), ('U', 'unknown')], max_length=1, null=True),
        ),
    ]
