# Generated by Django 4.2.28 on 2026-02-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_package_packagetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageupdate',
            options={'ordering': ['oldpackage', 'newpackage']},
        ),
    ]
