# Generated by Django 4.2.28 on 2026-03-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_packageupdate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='epoch',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='release',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(max_length=128),
        ),
    ]
