# Generated by Django 4.2.28 on 2026-04-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_alter_package_epoch_alter_package_release_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='packageupdate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('name', 'epoch', 'version', 'release', 'arch', 'packagetype', 'category'), name='unique_package'),
        ),
        migrations.AddConstraint(
            model_name='packageupdate',
            constraint=models.UniqueConstraint(fields=('oldpackage', 'newpackage', 'security'), name='unique_packageupdate'),
        ),
    ]
