---
services:
  patchman:
    container_name: patchman
    image: furlongm/patchman:latest 
    restart: unless-stopped
    environment:
      TIMEZONE: America/New_York
      ADMIN_NAME: admin_name
      ADMIN_EMAIL: admin_mail@domain.tld
      DB_ENGINE: MySQL
      DB_DATABASE: patchman
      DB_USER: user
      DB_PASSWORD: changeme
      DB_HOST: patchman-db
      DB_PORT: 3306
      MEMCACHED_ADDR: memcached
      MEMCACHED_PORT: 11211
      CELERY_BROKER: redis
      CELERY_BROKER_PORT: 6379
    depends_on:
      - patchman-db
      - memcached
      - redis

  patchman-db:
    container_name: patchman-db
    image: mysql:latest
    restart: unless-stopped
    command: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: changeme 
      MYSQL_DATABASE: patchman 
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme

  memcached:
    container_name: memcached
    image: memcached:latest
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
