# Generated by Django 4.2.28 on 2026-02-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinearchitecture',
            options={'ordering': ['name'], 'verbose_name': 'Machine Architecture'},
        ),
        migrations.AlterModelOptions(
            name='packagearchitecture',
            options={'ordering': ['name'], 'verbose_name': 'Package Architecture'},
        ),
    ]
