# Generated by Django 3.2.19 on 2023-12-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accessed', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('tags', models.CharField(default='', max_length=255, null=True)),
                ('kernel', models.CharField(max_length=255, null=True)),
                ('arch', models.CharField(max_length=255, null=True)),
                ('os', models.CharField(max_length=255, null=True)),
                ('report_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=255, null=True)),
                ('useragent', models.CharField(max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('packages', models.TextField(blank=True, null=True)),
                ('sec_updates', models.TextField(blank=True, null=True)),
                ('bug_updates', models.TextField(blank=True, null=True)),
                ('repos', models.TextField(blank=True, null=True)),
                ('reboot', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'ordering': ('-created',),
            },
        ),
    ]
