# Generated by Django 4.2.19 on 2025-02-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='accessed',
        ),
    ]
