# Generated by Django 4.2.19 on 2025-03-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_migrate_to_tz_aware'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Reports'},
        ),
    ]
