#!/usr/bin/python

# Copyright 2016 Marcus Furlong <furlongm@gmail.com>
#
# This file is part of Patchman.
#
# Patchman is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 only.
#
# Patchman is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Patchman. If not, see <http://www.gnu.org/licenses/>

import os
import re
import io
from random import choice

main_settings_file = "/etc/patchman/settings.py"
main_settings_file_tmp = "/etc/patchman/settings.py.tmp"

settings_contents = io.open(main_settings_file, 'r', encoding="utf_8").read()
secret_key = ''.join([choice('abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)') for i in range(50)])
settings_contents = re.sub(r"(?<=SECRET_KEY = ')'", secret_key + "'", settings_contents)

fp = io.open(main_settings_file_tmp, 'w', encoding="utf_8")
fp.write(settings_contents)
fp.close()

os.rename(main_settings_file_tmp, main_settings_file)
