# Generated by Django 4.2.19 on 2025-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_cve_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cwe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
