# Generated by Django 4.2.19 on 2025-03-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_cve_description_alter_cwe_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cve',
            options={'ordering': ['cve_id']},
        ),
    ]
