# Generated by Django 4.2.19 on 2025-03-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_cve_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2000)),
            ],
            options={
                'unique_together': {('ref_type', 'url')},
            },
        ),
        migrations.AddField(
            model_name='cve',
            name='references',
            field=models.ManyToManyField(blank=True, to='security.reference'),
        ),
    ]
