# Generated by Django 4.2.19 on 2025-03-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_reference_cve_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cve',
            options={'ordering': ['-cve_id']},
        ),
        migrations.AlterUniqueTogether(
            name='cvss',
            unique_together={('score', 'severity', 'version', 'vector_string')},
        ),
    ]
