# Generated by Django 4.2.20 on 2025-04-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_alter_cve_options_alter_cvss_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cve',
            name='title',
        ),
    ]
