# Generated by Django 4.2.28 on 2026-02-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_remove_cve_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cwe',
            options={'ordering': ['cwe_id']},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['ref_type', 'url']},
        ),
    ]
