# Generated by Django 4.2.28 on 2026-03-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_alter_cwe_options_alter_reference_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvss',
            name='severity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cvss',
            name='vector_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
