# Generated by Django 4.2.28 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_alter_cvss_severity_alter_cvss_vector_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvss',
            name='vector_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
