# Generated by Django 4.2.28 on 2026-04-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_fix_cvss_vector_string_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cvss',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cvss',
            constraint=models.UniqueConstraint(fields=('score', 'severity', 'version', 'vector_string'), name='unique_cvss'),
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('ref_type', 'url'), name='unique_reference'),
        ),
    ]
