# Generated by Django 4.2.19 on 2025-03-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erratumreference',
            unique_together={('er_type', 'url')},
        ),
    ]
