# Generated by Django 4.2.19 on 2025-03-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_reference_cve_references'),
        ('errata', '0002_alter_erratumreference_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erratum',
            name='references',
        ),
        migrations.DeleteModel(
            name='ErratumReference',
        ),
        migrations.AddField(
            model_name='erratum',
            name='references',
            field=models.ManyToManyField(blank=True, to='security.Reference'),
        ),
    ]
