# Generated by Django 4.2.19 on 2025-03-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0003_delete_erratumreference_alter_erratum_references'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erratum',
            old_name='packages',
            new_name='fixed_packages',
        ),
    ]
