# Generated by Django 4.2.19 on 2025-03-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_package_options_alter_packagecategory_options_and_more'),
        ('errata', '0004_rename_packages_erratum_fixed_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='erratum',
            name='affected_packages',
            field=models.ManyToManyField(blank=True, related_name='affected_by_erratum', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='erratum',
            name='fixed_packages',
            field=models.ManyToManyField(blank=True, related_name='fixed_by_erratum', to='packages.package'),
        ),
    ]
