# Generated by Django 4.2.19 on 2025-03-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0005_erratum_affected_packages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erratum',
            options={'ordering': ['-issue_date', 'name'], 'verbose_name': 'Erratum', 'verbose_name_plural': 'Errata'},
        ),
    ]
