# Generated by Django 4.2.28 on 2026-02-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0007_alter_erratum_fixed_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='erratum',
            name='affected_packages_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='erratum',
            name='cves_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='erratum',
            name='fixed_packages_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='erratum',
            name='osreleases_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='erratum',
            name='references_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
