# Generated by Django 4.2.28 on 2026-05-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0009_backfill_cached_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erratum',
            name='synopsis',
            field=models.TextField(),
        ),
    ]
