name: Create deb and rpm packages

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      ref: github.ref
      with:
        fetch-depth: 0
    - run: |
        git fetch --prune --unshallow
    - name: Install build dependencies
      run: |
        sudo apt -y install python-setuptools debhelper dh-exec dh-python git-buildpackage
    - name: Build deb package
      run: |
        git branch -v
        gbp buildpackage --git-ignore-new --git-force-create -uc -us
    - uses: actions/upload-artifact@v1
      with:
        name: python-patchman.deb
        path: ../python-patchman_1.2.3-1_all.deb
