name: Create deb and rpm packages

on:
  release:
    types: [created]

jobs:
  build-and-upload-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - run: |
        git fetch --all
    - name: Install build dependencies
      run: |
        sudo apt -y install python-setuptools debhelper dh-exec dh-python git-buildpackage
    - name: Get version
      id: get-version
      run: |
        export version=$(<VERSION.txt)
        echo "::set-env name=verson::${version}"
    - name: Build deb package
      run: |
        gbp buildpackage --git-ignore-new --git-force-create --git-upstream-tree=SLOPPY -uc -us
    - uses: actions/upload-artifact@v1
      with:
        name: python-patchman_${{ steps.get-version.env.version }}-1_all.deb
        path: ../python-patchman_${{ steps.get-version.env.version }}-1_all.deb
