name: Create deb and rpm packages

on:
  release:
    types: [created]

jobs:
  build-and-upload-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - run: |
        git fetch --all
    - name: Install build dependencies
      run: |
        sudo apt -y install python-setuptools debhelper dh-exec dh-python git-buildpackage
    - name: Get version
      id: get_version
      run: |
        export version=$(<VERSION.txt)
        echo "::set-env name=verson::${version}"
        echo "::set-output name=version::${version}"
    - name: Build deb package
      run: |
        gbp buildpackage --git-ignore-new --git-force-create --git-upstream-tree=SLOPPY -uc -us
    - uses: actions/upload-artifact@v1
      with:
        name:  ${{ format('python-patchman_{0}-1_all.deb', steps.get_version.outputs.version) }}
        path: ../${{ format('python-patchman_{0}-1_all.deb', steps.get_version.outputs.version) }}
    - uses: actions/upload-artifact@v1
      with:
        name:  ${{ format('patchman-client_{0}-1_all.deb', env.version) }}
        path: ../${{ format('patchman-client_{0}-1_all.deb', env.version) }}
  
